# sites/_http_.conf

#
# Author: Michael Welter <me@mikinho.com> - https://github.com/mikinho
#

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    limit_conn conn_general 20;

    include includes/letsencrypt.conf;

    location / {
        return 444;
    }
}
