# sites/_https_.conf

#
# Author: Michael Welter <me@mikinho.com> - https://github.com/mikinho
#

server {
    listen 443 ssl default_server;
    listen 443 quic reuseport default_server rcvbuf=2m sndbuf=2m;

    listen [::]:443 ssl default_server;
    listen [::]:443 quic reuseport default_server rcvbuf=2m sndbuf=2m;

    server_name _;

    ssl_reject_handshake on;

    location / {
        return 421;
    }
}
