# .github/dependabot.yml

#
# Author: Michael Welter <me@mikinho.com> - https://github.com/mikinho
#

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
