; php-fpm/sites/sample_wp.conf
;
; Author: Michael Welter <me@mikinho.com> - https://github.com/mikinho

[global]
daemonize = no
error_log = /proc/self/fd/2
log_level = notice
systemd_interval = 10

include = /etc/php-fpm.d/pool/sample_wp.conf
