# nginx/includes/http.conf

#
# Author: Michael Welter <me@mikinho.com> - https://github.com/mikinho
#

listen 80;
listen [::]:80;

limit_conn conn_general 20;

location / {
    limit_req zone=req_general burst=30 nodelay;

    return 308 https://$server_name$request_uri;
}

include includes/letsencrypt.conf;
