# includes/php-fpm-by-tag.conf

#
# Author: Michael Welter <me@mikinho.com> - https://github.com/mikinho
#

try_files $fastcgi_script_name =404;

fastcgi_split_path_info ^(.+\.php)(/.*)$;

fastcgi_intercept_errors on;
fastcgi_index index.php;

include fastcgi_params;

fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
fastcgi_param PATH_INFO $fastcgi_path_info;
fastcgi_param HTTP_PROXY "";

fastcgi_buffer_size 32k;
fastcgi_buffers 16 16k;
fastcgi_busy_buffers_size 64k;

fastcgi_pass unix:/run/$site_tag/php-fpm.sock;
