# includes/quiet-common-requests.conf

#
# Author: Michael Welter <me@mikinho.com> - https://github.com/mikinho
#

location = /favicon.ico {
    log_not_found off;
    access_log off;
}

location = /robots.txt {
    log_not_found off;
    access_log off;
}
