# nginx/includes/redir.conf

#
# Author: Michael Welter <me@mikinho.com> - https://github.com/mikinho
#

# Redirect secondary domains to our primary domain
if ($host != $server_name) {
    return 308 https://$server_name$request_uri;
}
