# includes/relativeurls.conf

#
# Author: Michael Welter <me@mikinho.com> - https://github.com/mikinho
#

sub_filter_once off;
sub_filter 'src="http://$host/' 'src="/';
sub_filter 'src="https://$host/' 'src="/';
sub_filter "src='http://$host/" "src='/";
sub_filter "src='https://$host/" "src='/";
sub_filter 'srcset="http://$host/' 'srcset="/';
sub_filter 'srcset="https://$host/' 'srcset="/';
sub_filter "srcset='http://$host/" "srcset='/";
sub_filter "srcset='https://$host/" "srcset='/";
sub_filter 'href="http://$host/' 'href="/';
sub_filter 'href="https://$host/' 'href="/';
sub_filter "href='http://$host/" "href='/";
sub_filter "href='https://$host/" "href='/";
