# includes/secure.conf

#
# Author: Michael Welter <me@mikinho.com> - https://github.com/mikinho
#

# Prevent access to hidden files
location ~* /\.(?!well-known\/) {
    deny all;
}

# Prevent access to certain file extensions
location ~* \.(ini|log|conf)$ {
    deny all;
}
