# monit/systemd/monit.service.conf

#
# Author: Michael Welter <me@mikinho.com> - https://github.com/mikinho
#

[Service]
UMask=0077
RuntimeDirectory=%p
RuntimeDirectoryMode=0750
StateDirectory=%p
StateDirectoryMode=0700
LogsDirectory=%p
LogsDirectoryMode=0700
Restart=on-failure
RestartSec=5s
ExecReload=
ExecReload=/bin/kill -HUP $MAINPID
